package polymod.hscript._internal;

#if macro
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type;
import haxe.macro.Type.ClassType;
import polymod.util.MacroUtil;
#end
import haxe.rtti.Meta;

using StringTools;

/**
 * Provides a macro which, after types are generated, populates a list of classes which extend `polymod.hscript.HScriptedClass`.
 * We have to do weird shenanigans to make the data accessible at runtime though.
 */
class PolymodScriptClassMacro
{
  /**
   * The name for the Haxe resource that stores the abstract static field paths.
   */
  static inline final ABSTRACT_STATICS_RES_NAME:String = 'PolymodScriptClassMacro_AbstractStatics';

  /**
   * Returns a `Map<String, Class<Dynamic>>` which maps superclass paths to scripted classes.
   * So `class ScriptedStage extends Stage implements HScriptable` will be `"Stage" -> ScriptedStage`
   *
   * @return An expression containing a map of superclasses to their scripted classes
   */
  public static macro function listHScriptedClasses():ExprOf<Map<String, Class<Dynamic>>>
  {
    if (!onGenerateCallbackRegistered)
    {
      onGenerateCallbackRegistered = true;
      haxe.macro.Context.onGenerate(onGenerate);
    }

    return macro polymod.hscript._internal.PolymodScriptClassMacro.fetchHScriptedClasses();
  }

  /**
   * @return An expression containing a map of abstract classes to their implementations
   */
  public static macro function listAbstractImpls():ExprOf<Map<String, AbstractImplEntry>>
  {
    if (!onGenerateCallbackRegistered)
    {
      onGenerateCallbackRegistered = true;
      haxe.macro.Context.onGenerate(onGenerate);
    }

    return macro polymod.hscript._internal.PolymodScriptClassMacro.fetchAbstractImpls();
  }

  /**
   * @return An expression containing a map of abstract field names to
   *  the internal class, generated by Polymod, to store that value (accessible via Reflection).
   */
  public static macro function listAbstractStatics():ExprOf<Map<String, Class<Dynamic>>>
  {
    if (!onAfterTypingCallbackRegistered)
    {
      onAfterTypingCallbackRegistered = true;
      haxe.macro.Context.onAfterTyping(onAfterTyping);
    }

    if (!onGenerateCallbackRegistered)
    {
      onGenerateCallbackRegistered = true;
      haxe.macro.Context.onGenerate(onGenerate);
    }

    return macro polymod.hscript._internal.PolymodScriptClassMacro.fetchAbstractStatics();
  }

  /**
   * @return An expression containing a map of each typedef name to
   *  the underlying class type.
   */
  public static macro function listTypedefs():ExprOf<Map<String, Class<Dynamic>>>
  {
    if (!onGenerateCallbackRegistered)
    {
      onGenerateCallbackRegistered = true;
      haxe.macro.Context.onGenerate(onGenerate);
    }

    return macro polymod.hscript._internal.PolymodScriptClassMacro.fetchTypedefs();
  }

  #if macro
  static var onGenerateCallbackRegistered:Bool = false;
  static var onAfterTypingCallbackRegistered:Bool = false;

  static function onGenerate(allTypes:Array<haxe.macro.Type>)
  {
    // Reset these, since onGenerate persists across multiple builds.
    var hscriptedClassType:ClassType = MacroUtil.getClassType('polymod.hscript.HScriptedClass');

    var hscriptedClassEntries:Array<Expr> = [];
    var abstractImplEntries:Array<Expr> = [];
    var abstractStaticEntries:Array<{}> = [];
    var typedefEntries:Array<Expr> = [];

    var startTime:Float = Sys.time();

    for (type in allTypes)
    {
      switch (type)
      {
        case TInst(t, _params):
          // Parse classes to check if they are `HScriptedClass` implementations, for processing later.

          var classType:ClassType = t.get();
          var classPath:String = '${classType.pack.concat([classType.name]).join(".")}';

          if (classType.isInterface)
          {
            // Ignore interfaces.
          }
          else if (MacroUtil.implementsInterface(classType, hscriptedClassType))
          {
            var superClass:Null<ClassType> = classType.superClass != null ? classType.superClass.t.get() : null;

            if (superClass == null) throw 'No superclass for ' + classPath;

            var superClassPath:String = '${superClass.pack.concat([superClass.name]).join(".")}';
            var entryData = [macro $v{superClassPath}, macro $v{classPath}];
            hscriptedClassEntries.push(macro $a{entryData});
          }

        case TType(t, _params):
          var typedefType:DefType = t.get();
          var typedefPath:String = t.toString();
          var typedefTarget:Type = Context.followWithAbstracts(type);

          switch (typedefTarget)
          {
            case TAnonymous(_):
              // Ignore typedefs to anonymous structures.
              continue;
            case TDynamic(_):
              // Ignore typedefs to Dynamic.
              continue;
            case TFun(_args, _ret):
              // Ignore typedefs to functions.
              continue;

            case TAbstract(t, _params):
              var targetPath:String = t.toString();

              var entryData = [macro $v{typedefPath}, macro $v{targetPath}];

              typedefEntries.push(macro $a{entryData});

            case TEnum(t, _params):
              var targetEnum:EnumType = t.get();
              var targetEnumPath:String = '${targetEnum.pack.concat([targetEnum.name]).join(".")}';

              var entryData = [macro $v{typedefPath}, macro $v{targetEnumPath}];

              typedefEntries.push(macro $a{entryData});

            case TInst(t, _params):
              var targetClass:ClassType = t.get();
              var targetClassPath:String = '${targetClass.pack.concat([targetClass.name]).join(".")}';

              var entryData = [macro $v{typedefPath}, macro $v{targetClassPath}];

              typedefEntries.push(macro $a{entryData});

            default:
              // Unknown typedef target type?
              trace('TYPEDEF: ${typedefPath} -> ${typedefTarget}');
          }

        case TAbstract(t, _params):
          // Perform additional processing on abstracts classes to ensure they can be accessed at runtime.

          var abstractPath:String = t.toString();
          var abstractType = t.get();
          var abstractImpl = abstractType.impl?.get();

          if (abstractImpl == null)
          {
            // If the abstract doesn't have an implementation, it's usually an extern or something, so we always want to ignore it.
            continue;
          }

          var abstractImplPath:String = abstractType.impl?.toString() ?? '';

          var entryData = [macro $v{abstractPath}, macro $v{abstractImplPath}];

          abstractImplEntries.push(macro $a{entryData});

          for (field in abstractImpl.statics.get())
          {
            switch (field.type)
            {
              case TAbstract(_, _):
                //
              case TType(_, _):
                //
              default:
                continue;
            }

            var key:String = '${abstractImplPath}.${field.name}';

            if (!staticFieldToClass.exists(key))
            {
              continue;
            }

            var staticEntryData =
              {
                fieldPath: key,
                reflectClassPath: staticFieldToClass[key]
              };

            abstractStaticEntries.push(staticEntryData);
          }
        default:
          continue;
      }
    }

    var endTime:Float = Sys.time();

    var duration:Float = endTime - startTime;

    Context.info('PolymodScriptClassMacro: '
      + 'Registered ${hscriptedClassEntries.length} HScriptedClasses, '
      + '${abstractImplEntries.length} abstract impls, '
      + '${abstractStaticEntries.length} abstract statics, '
      + '${typedefEntries.length} typedefs '
      + 'in ${duration} sec.',
      Context.currentPos());

    var polymodScriptClassClassType:ClassType = MacroUtil.getClassType('polymod.hscript._internal.PolymodScriptClassMacro');
    polymodScriptClassClassType.meta.remove('hscriptedClasses');
    polymodScriptClassClassType.meta.add('hscriptedClasses', hscriptedClassEntries, Context.currentPos());
    polymodScriptClassClassType.meta.remove('abstractImpls');
    polymodScriptClassClassType.meta.add('abstractImpls', abstractImplEntries, Context.currentPos());
    polymodScriptClassClassType.meta.remove('typedefs');
    polymodScriptClassClassType.meta.add('typedefs', typedefEntries, Context.currentPos());

    // It can get VERY BIG so we have to resort to store it as a resource instead.
    var absStaticsData:String = haxe.Serializer.run(abstractStaticEntries);
    Context.addResource(ABSTRACT_STATICS_RES_NAME, haxe.io.Bytes.ofString(absStaticsData));
  }

  static var iteration:Int = 0;
  static var staticFieldToClass:Map<String, String> = [];

  static function onAfterTyping(types:Array<ModuleType>):Void
  {
    var fields:Array<Field> = [];

    var startTime:Float = Sys.time();

    for (type in types)
    {
      switch (type)
      {
        case TAbstract(a):
          var abstractPath = a.toString();
          var abstractType = a.get();

          if (abstractType.impl == null)
          {
            // Only a few classes end up here, generally ones that are implemented directly in code.
            // Includes like StdTypes.Float, StdTypes.Dynamic, StdTypes.Void, cpp.Int16, cpp.SizeT, Class, Enum
            continue;
          }
          else
          {
            var abstractImplPath = abstractType.impl.toString();
            var abstractImplType = abstractType.impl.get();
            var abstractImplStatics:Array<ClassField> = abstractImplType.statics.get();

            for (field in abstractImplStatics)
            {
              switch (field.kind)
              {
                case FVar(read, write):
                  var canGet:Bool = read == AccInline || read == AccNormal;
                  if (read == AccCall)
                  {
                    var getter:Null<ClassField> = null;
                    for (f in abstractImplStatics)
                    {
                      if (f.name == 'get_${field.name}')
                      {
                        getter = f;
                        break;
                      }
                    }

                    if (getter == null)
                    {
                      throw 'Getter is null?';
                    }

                    switch (getter.type)
                    {
                      case TFun(args, _):
                        if (args.length != 0) continue;
                      default:
                        throw 'Getter has an unknown type?';
                    }

                    canGet = true;
                  }

                  var canSet:Bool = write == AccNormal;
                  if (write == AccCall)
                  {
                    var setter:Null<ClassField> = null;
                    for (f in abstractImplType.statics.get())
                    {
                      if (f.name == 'set_${field.name}')
                      {
                        setter = f;
                        break;
                      }
                    }

                    if (setter == null)
                    {
                      throw 'Setter is null?';
                    }

                    switch (setter.type)
                    {
                      case TFun(args, _):
                        if (args.length != 1) continue;
                      default:
                        throw 'Setter has an unknown type?';
                    }

                    canSet = true;
                  }

                  if (canGet || canSet)
                  {
                    var fieldName:String = '${abstractImplPath.replace('.', '_')}_${field.name}';

                    fields.push(
                      {
                        pos: Context.currentPos(),
                        name: fieldName,
                        access: [Access.APublic, Access.AStatic],
                        kind: FProp(canGet ? 'get' : 'never', canSet ? 'set' : 'never', (macro :Dynamic), null)
                      });

                    var fieldExpr:Expr = null;
                    try
                    {
                      // when this fails, this should mean that we are dealing with an enum abstract
                      // so we need to handle it differently
                      var fullPath:String = '${abstractType.module}.${abstractType.name}';
                      Context.getType(fullPath);
                      fieldExpr = Context.parse('${fullPath}.${field.name}', Context.currentPos());
                    }
                    catch (_)
                    {
                      fieldExpr = Context.getTypedExpr(field.expr());
                    }

                    if (canGet)
                    {
                      fields.push(
                        {
                          pos: Context.currentPos(),
                          name: 'get_${fieldName}',
                          access: [Access.APublic, Access.AStatic],
                          kind: FFun(
                            {
                              args: [],
                              ret: null,
                              expr: macro
                              {@:privateAccess return ${fieldExpr};}
                            })
                        });
                    }

                    if (canSet)
                    {
                      fields.push(
                        {
                          pos: Context.currentPos(),
                          name: 'set_${fieldName}',
                          access: [Access.APublic, Access.AStatic],
                          kind: FFun(
                            {
                              args: [
                                {name: 'value'}],
                              ret: null,
                              expr: macro
                              {@:privateAccess return ${fieldExpr} = value;}
                            })
                        });
                    }

                    staticFieldToClass.set('${abstractImplPath}.${field.name}', 'polymod.hscript._internal.AbstractStaticMembers_${iteration}');
                  }

                case FMethod(k):
                  // Skip methods, since we will be able to access the implementation class directly via Reflection.
                  continue;

                default:
                  continue;
              }
            }
          }
        default:
          continue;
      }
    }

    if (fields.length == 0)
    {
      return;
    }

    Context.defineType(
      {
        pos: Context.currentPos(),
        pack: ['polymod', 'hscript', '_internal'],
        name: 'AbstractStaticMembers_${iteration}',
        kind: TDClass(null, [], false, false, false),
        fields: fields
      });

    var endTime:Float = Sys.time();

    var duration:Float = endTime - startTime;

    Context.info('PolymodScriptClassMacro: Processed ${fields.length} static fields in ${duration} sec (iteration #${iteration}).', Context.currentPos());

    iteration++;
  }
  #end

  public static function fetchHScriptedClasses():Map<String, Class<Dynamic>>
  {
    var metaData = Meta.getType(PolymodScriptClassMacro);

    if (metaData.hscriptedClasses != null)
    {
      // trace('Got hscriptedClasses: ' + metaData.hscriptedClasses);

      var result:Map<String, Class<Dynamic>> = [];

      // Each element is formatted as `[superClassPath, classPath]`.

      for (element in metaData.hscriptedClasses)
      {
        if (element.length != 2)
        {
          throw 'Malformed element in hscriptedClasses: ' + element;
        }

        var superClassPath:String = element[0];
        var classPath:String = element[1];
        var classType:Class<Dynamic> = cast Type.resolveClass(classPath);
        result.set(superClassPath, classType);
      }

      return result;
    }
    else
    {
      throw 'No hscriptedClasses found in PolymodScriptClassMacro!';
    }
  }

  public static function fetchAbstractImpls():Map<String, AbstractImplEntry>
  {
    var metaData = Meta.getType(PolymodScriptClassMacro);

    if (metaData.abstractImpls != null)
    {
      var result:Map<String, AbstractImplEntry> = [];

      // Each element is formatted as `[abstractPath, abstractImplPath]`.

      for (element in metaData.abstractImpls)
      {
        if (element.length != 2)
        {
          throw 'Malformed element in abstractImpls: ' + element;
        }

        var abstractPath:String = element[0];
        var abstractImplPath:String = element[1];
        #if js
        var abstractImplType:Class<Dynamic> = resolveClass(abstractPath);

        if (abstractImplType == null)
        {
          throw 'Could not resolve ' + abstractPath;
        }
        #else
        var abstractImplType:Class<Dynamic> = cast Type.resolveClass(abstractImplPath);

        if (abstractImplType == null)
        {
          // If the abstract type was found at compile time, but couldn't resolve at runtime,
          // it probably got optimized out.
          // We'll have to construct a PolymodStaticAbstractReference for it later.
        }
        #end

        result.set(abstractPath,
          {
            cls: abstractImplType,
            clsName: abstractImplPath
          });
      }

      return result;
    }
    else
    {
      throw 'No abstractImpls found in PolymodScriptClassMacro!';
    }
  }

  public static function fetchAbstractStatics():Map<String, Class<Dynamic>>
  {
    var resDataContent:Null<String> = haxe.Resource.getString(ABSTRACT_STATICS_RES_NAME);
    if (resDataContent == null)
    {
      throw '"$ABSTRACT_STATICS_RES_NAME" resource not found!';
    }
    var abstractStatics:Array<{fieldPath:String, reflectClassPath:String}> = cast haxe.Unserializer.run(resDataContent);

    if (abstractStatics != null)
    {
      var result:Map<String, Class<Dynamic>> = [];

      // Each element is formatted as `[abstractPathImpl.fieldName, reflectClass]`.

      for (element in abstractStatics)
      {
        if ((element.fieldPath?.length ?? 0) == 0 || (element.reflectClassPath?.length ?? 0) == 0)
        {
          throw 'Malformed element in abstractStatics: ' + element;
        }

        var reflectClass:Class<Dynamic> = cast Type.resolveClass(element.reflectClassPath);

        result.set(element.fieldPath, reflectClass);
      }

      return result;
    }
    else
    {
      throw 'No abstractStatics found in "${ABSTRACT_STATICS_RES_NAME}" resource!';
    }
  }

  public static function fetchTypedefs():Map<String, Class<Dynamic>>
  {
    var metaData = Meta.getType(PolymodScriptClassMacro);

    if (metaData.typedefs != null)
    {
      var result:Map<String, Class<Dynamic>> = [];

      for (element in metaData.typedefs)
      {
        if (element.length != 2)
        {
          throw 'Malformed element in typedefs: ' + element;
        }

        var fieldPath:String = element[0];
        var reflectClassPath:String = element[1];
        var reflectClass:Class<Dynamic> = cast Type.resolveClass(reflectClassPath);

        result.set(fieldPath, reflectClass);
      }

      return result;
    }
    else
    {
      throw 'No typedefs found in PolymodScriptClassMacro!';
    }
  }

  #if js
  static var PACKAGE_NAME_INVALID = ~/[^.a-zA-Z0-9]/;

  // Fucked up workaround, volatile and could break at any moment.
  static function resolveClass(clsName:String):Class<Dynamic>
  {
    // Sanitize just in case someone tries to exploit this.
    var sanitizedName = PACKAGE_NAME_INVALID.replace(clsName, '');
    var parsedName = StringTools.replace(sanitizedName, '.', '_');
    return js.Syntax.code('eval({0})', parsedName);
  }
  #end
}

typedef AbstractImplEntry =
{
  cls:Class<Dynamic>,
  clsName:String,
};
